// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen_Weather
void ui_Screen_Weather_screen_init(void);
void ui_event_Screen_Weather(lv_event_t * e);
lv_obj_t * ui_Screen_Weather;
lv_obj_t * ui_Weather_Image_background;
lv_obj_t * ui_Weather_Image_Image29;
lv_obj_t * ui_Weather_Container_Container1;
lv_obj_t * ui_Weather_Panel_Panel1;
lv_obj_t * ui_Weather_Image_Image13;
lv_obj_t * ui_Weather_Image_Image14;
lv_obj_t * ui_Weather_Image_Image2;
lv_obj_t * ui_Weather_Image_Image15;
lv_obj_t * ui_Weather_Image_Image4;
lv_obj_t * ui_Weather_Label_Label8;
lv_obj_t * ui_Weather_Label_Label5;
lv_obj_t * ui_Weather_Label_Label9;
lv_obj_t * ui_Weather_Label_Label10;
lv_obj_t * ui_Weather_Label_Label11;
lv_obj_t * ui_Weather_Label_Label12;
lv_obj_t * ui_Weather_Label_Label13;
lv_obj_t * ui_Weather_Label_Label14;
lv_obj_t * ui_Weather_Label_Label15;
lv_obj_t * ui_Weather_Label_Label16;
lv_obj_t * ui_Weather_Panel_Panel3;
lv_obj_t * ui_Weather_Label_Label17;
lv_obj_t * ui_Weather_Label_Label18;
lv_obj_t * ui_Weather_Label_Label19;
lv_obj_t * ui_Weather_Label_Label20;
lv_obj_t * ui_Weather_Label_Label21;
lv_obj_t * ui_Weather_Label_Label22;
lv_obj_t * ui_Weather_Image_Image16;
lv_obj_t * ui_Weather_Image_Image5;
lv_obj_t * ui_Weather_Image_Image18;
lv_obj_t * ui_Weather_Image_Image19;
lv_obj_t * ui_Weather_Image_Image20;
lv_obj_t * ui_Weather_Label_Label23;
lv_obj_t * ui_Weather_Label_Label24;
lv_obj_t * ui_Weather_Label_Label25;
lv_obj_t * ui_Weather_Label_Label26;
lv_obj_t * ui_Weather_Label_Label27;
lv_obj_t * ui_Weather_Label_Label28;
lv_obj_t * ui_Weather_Label_Label29;
lv_obj_t * ui_Weather_Label_Label30;
lv_obj_t * ui_Weather_Label_Label31;
lv_obj_t * ui_Weather_Label_Label32;
lv_obj_t * ui_Weather_Label_Label6;
lv_obj_t * ui_Weather_Label_Label7;
lv_obj_t * ui_Weather_Label_Label2;
lv_obj_t * ui_Weather_Label_Label3;
lv_obj_t * ui_Weather_Label_Label4;
lv_obj_t * ui_Weather_Image_Image23;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Weather2
void ui_Screen_Weather2_screen_init(void);
void ui_event_Screen_Weather2(lv_event_t * e);
lv_obj_t * ui_Screen_Weather2;
lv_obj_t * ui_Weather2_Image_Image25;
lv_obj_t * ui_Weather2_Container_Container2;
lv_obj_t * ui_Weather2_Panel_Panel2;
lv_obj_t * ui_Weather2_Image_Image9;
lv_obj_t * ui_Weather2_Image_Image10;
lv_obj_t * ui_Weather2_Label_Label1;
lv_obj_t * ui_Weather2_Label_Label33;
lv_obj_t * ui_Weather2_Label_Label34;
lv_obj_t * ui_Weather2_Label_Label35;
lv_obj_t * ui_Weather2_Label_Label36;
lv_obj_t * ui_Weather2_Label_Label37;
lv_obj_t * ui_Weather2_Label_Label38;
lv_obj_t * ui_Weather2_Label_Label39;
lv_obj_t * ui_Weather2_Label_Label40;
lv_obj_t * ui_Weather2_Label_Label41;
lv_obj_t * ui_Weather2_Image_Image26;
lv_obj_t * ui_Weather2_Image_Image6;
lv_obj_t * ui_Weather2_Image_Image7;
lv_obj_t * ui_Weather2_Panel_Panel4;
lv_obj_t * ui_Weather2_Label_Label42;
lv_obj_t * ui_Weather2_Label_Label43;
lv_obj_t * ui_Weather2_Label_Label44;
lv_obj_t * ui_Weather2_Label_Label45;
lv_obj_t * ui_Weather2_Label_Label46;
lv_obj_t * ui_Weather2_Label_Label47;
lv_obj_t * ui_Weather2_Image_Image12;
lv_obj_t * ui_Weather2_Image_Image17;
lv_obj_t * ui_Weather2_Image_Image21;
lv_obj_t * ui_Weather2_Image_Image22;
lv_obj_t * ui_Weather2_Label_Label48;
lv_obj_t * ui_Weather2_Label_Label49;
lv_obj_t * ui_Weather2_Label_Label50;
lv_obj_t * ui_Weather2_Label_Label51;
lv_obj_t * ui_Weather2_Label_Label52;
lv_obj_t * ui_Weather2_Label_Label53;
lv_obj_t * ui_Weather2_Label_Label54;
lv_obj_t * ui_Weather2_Label_Label55;
lv_obj_t * ui_Weather2_Label_Label56;
lv_obj_t * ui_Weather2_Label_Label57;
lv_obj_t * ui_Weather2_Image_Image28;
lv_obj_t * ui_Weather2_Label_Label58;
lv_obj_t * ui_Weather2_Label_Label59;
lv_obj_t * ui_Weather2_Label_Label60;
lv_obj_t * ui_Weather2_Label_Label61;
lv_obj_t * ui_Weather2_Label_Label62;
lv_obj_t * ui_Weather2_Image_Image27;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_Weather2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen_Weather2_screen_init);
    }
}

void ui_event_Screen_Weather2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_Weather, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_Weather_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void weather_app_conf_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Weather_screen_init();
    ui_Screen_Weather2_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Weather);
}
