// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "esp_brookesia.h"
#include "ui_events.h"


// SCREEN: ui_Screen_Weather
void ui_Screen_Weather_screen_init(void);
void ui_event_Screen_Weather(lv_event_t * e);
extern lv_obj_t * ui_Screen_Weather;
extern lv_obj_t * ui_Weather_Image_background;
extern lv_obj_t * ui_Weather_Image_Image29;
extern lv_obj_t * ui_Weather_Container_Container1;
extern lv_obj_t * ui_Weather_Panel_Panel1;
extern lv_obj_t * ui_Weather_Image_Image13;
extern lv_obj_t * ui_Weather_Image_Image14;
extern lv_obj_t * ui_Weather_Image_Image2;
extern lv_obj_t * ui_Weather_Image_Image15;
extern lv_obj_t * ui_Weather_Image_Image4;
extern lv_obj_t * ui_Weather_Label_Label8;
extern lv_obj_t * ui_Weather_Label_Label5;
extern lv_obj_t * ui_Weather_Label_Label9;
extern lv_obj_t * ui_Weather_Label_Label10;
extern lv_obj_t * ui_Weather_Label_Label11;
extern lv_obj_t * ui_Weather_Label_Label12;
extern lv_obj_t * ui_Weather_Label_Label13;
extern lv_obj_t * ui_Weather_Label_Label14;
extern lv_obj_t * ui_Weather_Label_Label15;
extern lv_obj_t * ui_Weather_Label_Label16;
extern lv_obj_t * ui_Weather_Panel_Panel3;
extern lv_obj_t * ui_Weather_Label_Label17;
extern lv_obj_t * ui_Weather_Label_Label18;
extern lv_obj_t * ui_Weather_Label_Label19;
extern lv_obj_t * ui_Weather_Label_Label20;
extern lv_obj_t * ui_Weather_Label_Label21;
extern lv_obj_t * ui_Weather_Label_Label22;
extern lv_obj_t * ui_Weather_Image_Image16;
extern lv_obj_t * ui_Weather_Image_Image5;
extern lv_obj_t * ui_Weather_Image_Image18;
extern lv_obj_t * ui_Weather_Image_Image19;
extern lv_obj_t * ui_Weather_Image_Image20;
extern lv_obj_t * ui_Weather_Label_Label23;
extern lv_obj_t * ui_Weather_Label_Label24;
extern lv_obj_t * ui_Weather_Label_Label25;
extern lv_obj_t * ui_Weather_Label_Label26;
extern lv_obj_t * ui_Weather_Label_Label27;
extern lv_obj_t * ui_Weather_Label_Label28;
extern lv_obj_t * ui_Weather_Label_Label29;
extern lv_obj_t * ui_Weather_Label_Label30;
extern lv_obj_t * ui_Weather_Label_Label31;
extern lv_obj_t * ui_Weather_Label_Label32;
extern lv_obj_t * ui_Weather_Label_Label6;
extern lv_obj_t * ui_Weather_Label_Label7;
extern lv_obj_t * ui_Weather_Label_Label2;
extern lv_obj_t * ui_Weather_Label_Label3;
extern lv_obj_t * ui_Weather_Label_Label4;
extern lv_obj_t * ui_Weather_Image_Image23;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Weather2
void ui_Screen_Weather2_screen_init(void);
void ui_event_Screen_Weather2(lv_event_t * e);
extern lv_obj_t * ui_Screen_Weather2;
extern lv_obj_t * ui_Weather2_Image_Image25;
extern lv_obj_t * ui_Weather2_Container_Container2;
extern lv_obj_t * ui_Weather2_Panel_Panel2;
extern lv_obj_t * ui_Weather2_Image_Image9;
extern lv_obj_t * ui_Weather2_Image_Image10;
extern lv_obj_t * ui_Weather2_Label_Label1;
extern lv_obj_t * ui_Weather2_Label_Label33;
extern lv_obj_t * ui_Weather2_Label_Label34;
extern lv_obj_t * ui_Weather2_Label_Label35;
extern lv_obj_t * ui_Weather2_Label_Label36;
extern lv_obj_t * ui_Weather2_Label_Label37;
extern lv_obj_t * ui_Weather2_Label_Label38;
extern lv_obj_t * ui_Weather2_Label_Label39;
extern lv_obj_t * ui_Weather2_Label_Label40;
extern lv_obj_t * ui_Weather2_Label_Label41;
extern lv_obj_t * ui_Weather2_Image_Image26;
extern lv_obj_t * ui_Weather2_Image_Image6;
extern lv_obj_t * ui_Weather2_Image_Image7;
extern lv_obj_t * ui_Weather2_Panel_Panel4;
extern lv_obj_t * ui_Weather2_Label_Label42;
extern lv_obj_t * ui_Weather2_Label_Label43;
extern lv_obj_t * ui_Weather2_Label_Label44;
extern lv_obj_t * ui_Weather2_Label_Label45;
extern lv_obj_t * ui_Weather2_Label_Label46;
extern lv_obj_t * ui_Weather2_Label_Label47;
extern lv_obj_t * ui_Weather2_Image_Image12;
extern lv_obj_t * ui_Weather2_Image_Image17;
extern lv_obj_t * ui_Weather2_Image_Image21;
extern lv_obj_t * ui_Weather2_Image_Image22;
extern lv_obj_t * ui_Weather2_Label_Label48;
extern lv_obj_t * ui_Weather2_Label_Label49;
extern lv_obj_t * ui_Weather2_Label_Label50;
extern lv_obj_t * ui_Weather2_Label_Label51;
extern lv_obj_t * ui_Weather2_Label_Label52;
extern lv_obj_t * ui_Weather2_Label_Label53;
extern lv_obj_t * ui_Weather2_Label_Label54;
extern lv_obj_t * ui_Weather2_Label_Label55;
extern lv_obj_t * ui_Weather2_Label_Label56;
extern lv_obj_t * ui_Weather2_Label_Label57;
extern lv_obj_t * ui_Weather2_Image_Image28;
extern lv_obj_t * ui_Weather2_Label_Label58;
extern lv_obj_t * ui_Weather2_Label_Label59;
extern lv_obj_t * ui_Weather2_Label_Label60;
extern lv_obj_t * ui_Weather2_Label_Label61;
extern lv_obj_t * ui_Weather2_Label_Label62;
extern lv_obj_t * ui_Weather2_Image_Image27;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sunny_nosun_png);    // assets/sunny_nosun.png
LV_IMG_DECLARE(ui_img_sun_resize_png);    // assets/sun_resize.png
LV_IMG_DECLARE(ui_img_cloudy_resize_png);    // assets/cloudy_resize.png
LV_IMG_DECLARE(ui_img_calender_png);    // assets/calender.png
LV_IMG_DECLARE(ui_img_rain_background_png);    // assets/rain_background.png
LV_IMG_DECLARE(ui_img_rainingslightly_resize_png);    // assets/rainingslightly_resize.png
LV_IMG_DECLARE(ui_img_calender_noclor_png);    // assets/calender_noClor.png

// FONTS
LV_FONT_DECLARE(ui_font_Fontmax);
LV_FONT_DECLARE(ui_font_Font200);

// UI INIT
void weather_app_conf_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
