// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Weather_screen_init(void)
{
    ui_Screen_Weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_background = lv_img_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Image_background, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_background, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weather_Image_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image29 = lv_img_create(ui_Screen_Weather);
    lv_img_set_src(ui_Weather_Image_Image29, &ui_img_sunny_nosun_png);
    lv_obj_set_width(ui_Weather_Image_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weather_Image_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Container_Container1 = lv_obj_create(ui_Screen_Weather);
    lv_obj_remove_style_all(ui_Weather_Container_Container1);
    lv_obj_set_width(ui_Weather_Container_Container1, 478);
    lv_obj_set_height(ui_Weather_Container_Container1, 234);
    lv_obj_set_x(ui_Weather_Container_Container1, -61);
    lv_obj_set_y(ui_Weather_Container_Container1, -139);
    lv_obj_set_align(ui_Weather_Container_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather_Container_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Panel_Panel1 = lv_obj_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Panel_Panel1, 626);
    lv_obj_set_height(ui_Weather_Panel_Panel1, 238);
    lv_obj_set_x(ui_Weather_Panel_Panel1, 7);
    lv_obj_set_y(ui_Weather_Panel_Panel1, -15);
    lv_obj_set_align(ui_Weather_Panel_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather_Panel_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Panel_Panel1, lv_color_hex(0xBAC4F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Panel_Panel1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather_Panel_Panel1, lv_color_hex(0x5B76BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather_Panel_Panel1, lv_color_hex(0x2E3CDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather_Panel_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_Image13 = lv_img_create(ui_Weather_Panel_Panel1);
    lv_img_set_src(ui_Weather_Image_Image13, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image13, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image13, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather_Image_Image13, -222);
    lv_obj_set_y(ui_Weather_Image_Image13, 8);
    lv_obj_set_align(ui_Weather_Image_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image14 = lv_img_create(ui_Weather_Panel_Panel1);
    lv_img_set_src(ui_Weather_Image_Image14, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image14, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image14, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather_Image_Image14, -103);
    lv_obj_set_y(ui_Weather_Image_Image14, 72);
    lv_obj_set_align(ui_Weather_Image_Image14, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Weather_Image_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image2 = lv_img_create(ui_Weather_Panel_Panel1);
    lv_img_set_src(ui_Weather_Image_Image2, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather_Image_Image2, 13);
    lv_obj_set_y(ui_Weather_Image_Image2, 73);
    lv_obj_set_align(ui_Weather_Image_Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Weather_Image_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image15 = lv_img_create(ui_Weather_Panel_Panel1);
    lv_img_set_src(ui_Weather_Image_Image15, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image15, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image15, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather_Image_Image15, 124);
    lv_obj_set_y(ui_Weather_Image_Image15, 7);
    lv_obj_set_align(ui_Weather_Image_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image4 = lv_img_create(ui_Weather_Panel_Panel1);
    lv_img_set_src(ui_Weather_Image_Image4, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image4, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather_Image_Image4, 240);
    lv_obj_set_y(ui_Weather_Image_Image4, 6);
    lv_obj_set_align(ui_Weather_Image_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Label_Label8 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label8, -216);
    lv_obj_set_y(ui_Weather_Label_Label8, 69);
    lv_obj_set_align(ui_Weather_Label_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label8, "26°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label8, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label8, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label5 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label5, 244);
    lv_obj_set_y(ui_Weather_Label_Label5, 70);
    lv_obj_set_align(ui_Weather_Label_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label5, "21°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label5, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label9 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label9, 130);
    lv_obj_set_y(ui_Weather_Label_Label9, 71);
    lv_obj_set_align(ui_Weather_Label_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label9, "22°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label9, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label10 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label10, 21);
    lv_obj_set_y(ui_Weather_Label_Label10, 69);
    lv_obj_set_align(ui_Weather_Label_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label10, "22°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label10, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label11 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label11, -93);
    lv_obj_set_y(ui_Weather_Label_Label11, 68);
    lv_obj_set_align(ui_Weather_Label_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label11, "25°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label11, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label12 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label12, -229);
    lv_obj_set_y(ui_Weather_Label_Label12, -54);
    lv_obj_set_align(ui_Weather_Label_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label12, "Now");
    lv_obj_set_style_text_color(ui_Weather_Label_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label12, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label13 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label13, 235);
    lv_obj_set_y(ui_Weather_Label_Label13, -54);
    lv_obj_set_align(ui_Weather_Label_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label13, "18");
    lv_obj_set_style_text_color(ui_Weather_Label_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label13, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label14 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label14, 123);
    lv_obj_set_y(ui_Weather_Label_Label14, -55);
    lv_obj_set_align(ui_Weather_Label_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label14, "17");
    lv_obj_set_style_text_color(ui_Weather_Label_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label14, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label15 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label15, 11);
    lv_obj_set_y(ui_Weather_Label_Label15, -56);
    lv_obj_set_align(ui_Weather_Label_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label15, "16");
    lv_obj_set_style_text_color(ui_Weather_Label_Label15, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label15, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label16 = lv_label_create(ui_Weather_Panel_Panel1);
    lv_obj_set_width(ui_Weather_Label_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label16, -109);
    lv_obj_set_y(ui_Weather_Label_Label16, -56);
    lv_obj_set_align(ui_Weather_Label_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label16, "15");
    lv_obj_set_style_text_color(ui_Weather_Label_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label16, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Panel_Panel3 = lv_obj_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Panel_Panel3, 622);
    lv_obj_set_height(ui_Weather_Panel_Panel3, 461);
    lv_obj_set_x(ui_Weather_Panel_Panel3, 6);
    lv_obj_set_y(ui_Weather_Panel_Panel3, 363);
    lv_obj_set_align(ui_Weather_Panel_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather_Panel_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Panel_Panel3, lv_color_hex(0xBAC4F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Panel_Panel3, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather_Panel_Panel3, lv_color_hex(0x5B76BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather_Panel_Panel3, lv_color_hex(0x2E3CDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather_Panel_Panel3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label17 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label17, -55);
    lv_obj_set_y(ui_Weather_Label_Label17, -186);
    lv_obj_set_align(ui_Weather_Label_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label17, "10-DAT FORECAST");
    lv_obj_set_style_text_color(ui_Weather_Label_Label17, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label17, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label18 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label18, -202);
    lv_obj_set_y(ui_Weather_Label_Label18, -110);
    lv_obj_set_align(ui_Weather_Label_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label18, "Today");
    lv_obj_set_style_text_color(ui_Weather_Label_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label18, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label19 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label19, -204);
    lv_obj_set_y(ui_Weather_Label_Label19, 36);
    lv_obj_set_align(ui_Weather_Label_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label19, "Sun");
    lv_obj_set_style_text_color(ui_Weather_Label_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label19, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label20 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label20, -209);
    lv_obj_set_y(ui_Weather_Label_Label20, -31);
    lv_obj_set_align(ui_Weather_Label_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label20, "Sat");
    lv_obj_set_style_text_color(ui_Weather_Label_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label20, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label21 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label21, -203);
    lv_obj_set_y(ui_Weather_Label_Label21, 106);
    lv_obj_set_align(ui_Weather_Label_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label21, "Mon");
    lv_obj_set_style_text_color(ui_Weather_Label_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label21, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label22 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label22, -204);
    lv_obj_set_y(ui_Weather_Label_Label22, 175);
    lv_obj_set_align(ui_Weather_Label_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label22, "Tue");
    lv_obj_set_style_text_color(ui_Weather_Label_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label22, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_Image16 = lv_img_create(ui_Weather_Panel_Panel3);
    lv_img_set_src(ui_Weather_Image_Image16, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image16, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image16, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather_Image_Image16, -19);
    lv_obj_set_y(ui_Weather_Image_Image16, -105);
    lv_obj_set_align(ui_Weather_Image_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image5 = lv_img_create(ui_Weather_Panel_Panel3);
    lv_img_set_src(ui_Weather_Image_Image5, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image5, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather_Image_Image5, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather_Image_Image5, -19);
    lv_obj_set_y(ui_Weather_Image_Image5, -34);
    lv_obj_set_align(ui_Weather_Image_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image18 = lv_img_create(ui_Weather_Panel_Panel3);
    lv_img_set_src(ui_Weather_Image_Image18, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_Image18, -17);
    lv_obj_set_y(ui_Weather_Image_Image18, 34);
    lv_obj_set_align(ui_Weather_Image_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image19 = lv_img_create(ui_Weather_Panel_Panel3);
    lv_img_set_src(ui_Weather_Image_Image19, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_Image19, -17);
    lv_obj_set_y(ui_Weather_Image_Image19, 100);
    lv_obj_set_align(ui_Weather_Image_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Image_Image20 = lv_img_create(ui_Weather_Panel_Panel3);
    lv_img_set_src(ui_Weather_Image_Image20, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather_Image_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_Image20, -16);
    lv_obj_set_y(ui_Weather_Image_Image20, 175);
    lv_obj_set_align(ui_Weather_Image_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Label_Label23 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label23, 166);
    lv_obj_set_y(ui_Weather_Label_Label23, -110);
    lv_obj_set_align(ui_Weather_Label_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label23, "21° ~ 27°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label23, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label24 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label24, 167);
    lv_obj_set_y(ui_Weather_Label_Label24, 175);
    lv_obj_set_align(ui_Weather_Label_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label24, "24° ~ 27°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label24, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label25 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label25, 170);
    lv_obj_set_y(ui_Weather_Label_Label25, 104);
    lv_obj_set_align(ui_Weather_Label_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label25, "28° ~ 30°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label25, lv_color_hex(0xFEFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label25, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label26 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label26, 169);
    lv_obj_set_y(ui_Weather_Label_Label26, 30);
    lv_obj_set_align(ui_Weather_Label_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label26, "20° ~ 26°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label26, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label26, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label27 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label27, 170);
    lv_obj_set_y(ui_Weather_Label_Label27, -36);
    lv_obj_set_align(ui_Weather_Label_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label27, "23° ~ 30°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label27, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label27, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label28 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label28, 10);
    lv_obj_set_y(ui_Weather_Label_Label28, 133);
    lv_obj_set_align(ui_Weather_Label_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label28,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather_Label_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label28, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label29 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label29, -1);
    lv_obj_set_y(ui_Weather_Label_Label29, -158);
    lv_obj_set_align(ui_Weather_Label_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label29,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather_Label_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label29, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label30 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label30, 7);
    lv_obj_set_y(ui_Weather_Label_Label30, -74);
    lv_obj_set_align(ui_Weather_Label_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label30,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather_Label_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label30, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label31 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label31, 8);
    lv_obj_set_y(ui_Weather_Label_Label31, -9);
    lv_obj_set_align(ui_Weather_Label_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label31,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather_Label_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label31, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label32 = lv_label_create(ui_Weather_Panel_Panel3);
    lv_obj_set_width(ui_Weather_Label_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label32, 7);
    lv_obj_set_y(ui_Weather_Label_Label32, 64);
    lv_obj_set_align(ui_Weather_Label_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label32,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather_Label_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label32, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label6 = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label6, 20);
    lv_obj_set_y(ui_Weather_Label_Label6, -353);
    lv_obj_set_align(ui_Weather_Label_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label6, "26°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label6, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label6, &ui_font_Font200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Weather_Label_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Weather_Label_Label6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label7 = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label7, -15);
    lv_obj_set_y(ui_Weather_Label_Label7, -561);
    lv_obj_set_align(ui_Weather_Label_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label7, "My Location");
    lv_obj_set_style_text_color(ui_Weather_Label_Label7, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label2 = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label2, -16);
    lv_obj_set_y(ui_Weather_Label_Label2, -500);
    lv_obj_set_align(ui_Weather_Label_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label2, "Shanghai");
    lv_obj_set_style_text_color(ui_Weather_Label_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label3 = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label3, -21);
    lv_obj_set_y(ui_Weather_Label_Label3, -249);
    lv_obj_set_align(ui_Weather_Label_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label3, "Sunny");
    lv_obj_set_style_text_color(ui_Weather_Label_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Label4 = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Label4, -8);
    lv_obj_set_y(ui_Weather_Label_Label4, -186);
    lv_obj_set_align(ui_Weather_Label_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label_Label4, "H:27°  L:21°");
    lv_obj_set_style_text_color(ui_Weather_Label_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_Image23 = lv_img_create(ui_Screen_Weather);
    lv_img_set_src(ui_Weather_Image_Image23, &ui_img_calender_png);
    lv_obj_set_width(ui_Weather_Image_Image23, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Weather_Image_Image23, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather_Image_Image23, -246);
    lv_obj_set_y(ui_Weather_Image_Image23, 175);
    lv_obj_set_align(ui_Weather_Image_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen_Weather, ui_event_Screen_Weather, LV_EVENT_ALL, NULL);

}
