// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Weather2_screen_init(void)
{
    ui_Screen_Weather2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Weather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image25 = lv_img_create(ui_Screen_Weather2);
    lv_img_set_src(ui_Weather2_Image_Image25, &ui_img_rain_background_png);
    lv_obj_set_width(ui_Weather2_Image_Image25, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Weather2_Image_Image25, LV_SIZE_CONTENT);    /// 1536
    lv_obj_set_align(ui_Weather2_Image_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Container_Container2 = lv_obj_create(ui_Screen_Weather2);
    lv_obj_remove_style_all(ui_Weather2_Container_Container2);
    lv_obj_set_width(ui_Weather2_Container_Container2, 478);
    lv_obj_set_height(ui_Weather2_Container_Container2, 234);
    lv_obj_set_x(ui_Weather2_Container_Container2, -61);
    lv_obj_set_y(ui_Weather2_Container_Container2, -139);
    lv_obj_set_align(ui_Weather2_Container_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather2_Container_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Panel_Panel2 = lv_obj_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Panel_Panel2, 626);
    lv_obj_set_height(ui_Weather2_Panel_Panel2, 238);
    lv_obj_set_x(ui_Weather2_Panel_Panel2, 7);
    lv_obj_set_y(ui_Weather2_Panel_Panel2, -15);
    lv_obj_set_align(ui_Weather2_Panel_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather2_Panel_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather2_Panel_Panel2, lv_color_hex(0xBAC4F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather2_Panel_Panel2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather2_Panel_Panel2, lv_color_hex(0x5B76BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather2_Panel_Panel2, lv_color_hex(0x2E3CDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather2_Panel_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Image_Image9 = lv_img_create(ui_Weather2_Panel_Panel2);
    lv_img_set_src(ui_Weather2_Image_Image9, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image9, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image9, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather2_Image_Image9, 124);
    lv_obj_set_y(ui_Weather2_Image_Image9, 7);
    lv_obj_set_align(ui_Weather2_Image_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image10 = lv_img_create(ui_Weather2_Panel_Panel2);
    lv_img_set_src(ui_Weather2_Image_Image10, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image10, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image10, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather2_Image_Image10, 240);
    lv_obj_set_y(ui_Weather2_Image_Image10, 6);
    lv_obj_set_align(ui_Weather2_Image_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Label_Label1 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label1, -223);
    lv_obj_set_y(ui_Weather2_Label_Label1, 66);
    lv_obj_set_align(ui_Weather2_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label1, "24°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label1, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label33 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label33, 244);
    lv_obj_set_y(ui_Weather2_Label_Label33, 70);
    lv_obj_set_align(ui_Weather2_Label_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label33, "21°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label33, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label33, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label34 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label34, 130);
    lv_obj_set_y(ui_Weather2_Label_Label34, 71);
    lv_obj_set_align(ui_Weather2_Label_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label34, "22°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label34, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label34, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label35 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label35, 21);
    lv_obj_set_y(ui_Weather2_Label_Label35, 69);
    lv_obj_set_align(ui_Weather2_Label_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label35, "22°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label35, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label35, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label36 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label36, -93);
    lv_obj_set_y(ui_Weather2_Label_Label36, 68);
    lv_obj_set_align(ui_Weather2_Label_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label36, "25°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label36, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label37 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label37, -229);
    lv_obj_set_y(ui_Weather2_Label_Label37, -56);
    lv_obj_set_align(ui_Weather2_Label_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label37, "Now");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label37, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label38 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label38, 235);
    lv_obj_set_y(ui_Weather2_Label_Label38, -54);
    lv_obj_set_align(ui_Weather2_Label_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label38, "18");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label38, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label39 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label39, 123);
    lv_obj_set_y(ui_Weather2_Label_Label39, -55);
    lv_obj_set_align(ui_Weather2_Label_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label39, "17");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label39, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label39, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label40 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label40, 11);
    lv_obj_set_y(ui_Weather2_Label_Label40, -56);
    lv_obj_set_align(ui_Weather2_Label_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label40, "16");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label40, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label41 = lv_label_create(ui_Weather2_Panel_Panel2);
    lv_obj_set_width(ui_Weather2_Label_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label41, -109);
    lv_obj_set_y(ui_Weather2_Label_Label41, -56);
    lv_obj_set_align(ui_Weather2_Label_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label41, "15");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label41, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label41, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Image_Image26 = lv_img_create(ui_Weather2_Panel_Panel2);
    lv_img_set_src(ui_Weather2_Image_Image26, &ui_img_rainingslightly_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image26, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image26, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Weather2_Image_Image26, -228);
    lv_obj_set_y(ui_Weather2_Image_Image26, 4);
    lv_obj_set_align(ui_Weather2_Image_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image6 = lv_img_create(ui_Weather2_Panel_Panel2);
    lv_img_set_src(ui_Weather2_Image_Image6, &ui_img_rainingslightly_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image6, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image6, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Weather2_Image_Image6, -108);
    lv_obj_set_y(ui_Weather2_Image_Image6, 4);
    lv_obj_set_align(ui_Weather2_Image_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image7 = lv_img_create(ui_Weather2_Panel_Panel2);
    lv_img_set_src(ui_Weather2_Image_Image7, &ui_img_rainingslightly_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image7, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image7, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Weather2_Image_Image7, 13);
    lv_obj_set_y(ui_Weather2_Image_Image7, 4);
    lv_obj_set_align(ui_Weather2_Image_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Panel_Panel4 = lv_obj_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Panel_Panel4, 622);
    lv_obj_set_height(ui_Weather2_Panel_Panel4, 461);
    lv_obj_set_x(ui_Weather2_Panel_Panel4, 6);
    lv_obj_set_y(ui_Weather2_Panel_Panel4, 363);
    lv_obj_set_align(ui_Weather2_Panel_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather2_Panel_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather2_Panel_Panel4, lv_color_hex(0xBAC4F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather2_Panel_Panel4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather2_Panel_Panel4, lv_color_hex(0x5B76BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather2_Panel_Panel4, lv_color_hex(0x2E3CDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather2_Panel_Panel4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label42 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label42, -55);
    lv_obj_set_y(ui_Weather2_Label_Label42, -188);
    lv_obj_set_align(ui_Weather2_Label_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label42, "10-DAT FORECAST");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label42, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label43 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label43, -202);
    lv_obj_set_y(ui_Weather2_Label_Label43, -110);
    lv_obj_set_align(ui_Weather2_Label_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label43, "Today");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label43, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label44 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label44, -204);
    lv_obj_set_y(ui_Weather2_Label_Label44, 36);
    lv_obj_set_align(ui_Weather2_Label_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label44, "Sun");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label44, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label45 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label45, -209);
    lv_obj_set_y(ui_Weather2_Label_Label45, -31);
    lv_obj_set_align(ui_Weather2_Label_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label45, "Sat");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label45, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label45, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label46 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label46, -203);
    lv_obj_set_y(ui_Weather2_Label_Label46, 106);
    lv_obj_set_align(ui_Weather2_Label_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label46, "Mon");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label46, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label47 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label47, -204);
    lv_obj_set_y(ui_Weather2_Label_Label47, 175);
    lv_obj_set_align(ui_Weather2_Label_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label47, "Tue");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label47, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label47, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Image_Image12 = lv_img_create(ui_Weather2_Panel_Panel4);
    lv_img_set_src(ui_Weather2_Image_Image12, &ui_img_sun_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image12, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image12, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Weather2_Image_Image12, -19);
    lv_obj_set_y(ui_Weather2_Image_Image12, -34);
    lv_obj_set_align(ui_Weather2_Image_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image17 = lv_img_create(ui_Weather2_Panel_Panel4);
    lv_img_set_src(ui_Weather2_Image_Image17, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Image_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Image_Image17, -17);
    lv_obj_set_y(ui_Weather2_Image_Image17, 34);
    lv_obj_set_align(ui_Weather2_Image_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image21 = lv_img_create(ui_Weather2_Panel_Panel4);
    lv_img_set_src(ui_Weather2_Image_Image21, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Image_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Image_Image21, -16);
    lv_obj_set_y(ui_Weather2_Image_Image21, 104);
    lv_obj_set_align(ui_Weather2_Image_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Image_Image22 = lv_img_create(ui_Weather2_Panel_Panel4);
    lv_img_set_src(ui_Weather2_Image_Image22, &ui_img_cloudy_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Image_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Image_Image22, -15);
    lv_obj_set_y(ui_Weather2_Image_Image22, 176);
    lv_obj_set_align(ui_Weather2_Image_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Label_Label48 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label48, 162);
    lv_obj_set_y(ui_Weather2_Label_Label48, -110);
    lv_obj_set_align(ui_Weather2_Label_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label48, "21° ~ 27°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label48, lv_color_hex(0xFCF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label48, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label49 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label49, 170);
    lv_obj_set_y(ui_Weather2_Label_Label49, 175);
    lv_obj_set_align(ui_Weather2_Label_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label49, "24° ~ 27°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label49, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label50 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label50, 170);
    lv_obj_set_y(ui_Weather2_Label_Label50, 104);
    lv_obj_set_align(ui_Weather2_Label_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label50, "28° ~ 30°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label50, lv_color_hex(0xFFF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label50, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label51 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label51, 167);
    lv_obj_set_y(ui_Weather2_Label_Label51, 34);
    lv_obj_set_align(ui_Weather2_Label_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label51, "20° ~ 26°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label51, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label52 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label52, 167);
    lv_obj_set_y(ui_Weather2_Label_Label52, -35);
    lv_obj_set_align(ui_Weather2_Label_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label52, "23° ~ 30°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label52, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label52, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label53 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label53, 10);
    lv_obj_set_y(ui_Weather2_Label_Label53, 133);
    lv_obj_set_align(ui_Weather2_Label_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label53,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label53, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label54 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label54, -1);
    lv_obj_set_y(ui_Weather2_Label_Label54, -158);
    lv_obj_set_align(ui_Weather2_Label_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label54,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label54, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label55 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label55, 7);
    lv_obj_set_y(ui_Weather2_Label_Label55, -74);
    lv_obj_set_align(ui_Weather2_Label_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label55,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label55, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label55, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label56 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label56, 8);
    lv_obj_set_y(ui_Weather2_Label_Label56, -9);
    lv_obj_set_align(ui_Weather2_Label_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label56,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label56, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label57 = lv_label_create(ui_Weather2_Panel_Panel4);
    lv_obj_set_width(ui_Weather2_Label_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label57, 7);
    lv_obj_set_y(ui_Weather2_Label_Label57, 64);
    lv_obj_set_align(ui_Weather2_Label_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label57,
                      "______________________________________________________________________________");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label57, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label57, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Image_Image28 = lv_img_create(ui_Weather2_Panel_Panel4);
    lv_img_set_src(ui_Weather2_Image_Image28, &ui_img_rainingslightly_resize_png);
    lv_obj_set_width(ui_Weather2_Image_Image28, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Weather2_Image_Image28, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Weather2_Image_Image28, -23);
    lv_obj_set_y(ui_Weather2_Image_Image28, -112);
    lv_obj_set_align(ui_Weather2_Image_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather2_Label_Label58 = lv_label_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Label_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label58, 20);
    lv_obj_set_y(ui_Weather2_Label_Label58, -353);
    lv_obj_set_align(ui_Weather2_Label_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label58, "24°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label58, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label58, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label58, &ui_font_Font200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Weather2_Label_Label58, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Weather2_Label_Label58, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label59 = lv_label_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Label_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label59, -15);
    lv_obj_set_y(ui_Weather2_Label_Label59, -561);
    lv_obj_set_align(ui_Weather2_Label_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label59, "My Location");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label59, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label59, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label60 = lv_label_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Label_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label60, -16);
    lv_obj_set_y(ui_Weather2_Label_Label60, -500);
    lv_obj_set_align(ui_Weather2_Label_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label60, "Shanghai");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label60, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label61 = lv_label_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Label_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label61, -21);
    lv_obj_set_y(ui_Weather2_Label_Label61, -249);
    lv_obj_set_align(ui_Weather2_Label_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label61, "Sunny");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label61, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Label_Label62 = lv_label_create(ui_Screen_Weather2);
    lv_obj_set_width(ui_Weather2_Label_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather2_Label_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather2_Label_Label62, -8);
    lv_obj_set_y(ui_Weather2_Label_Label62, -186);
    lv_obj_set_align(ui_Weather2_Label_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather2_Label_Label62, "H:27°  L:21°");
    lv_obj_set_style_text_color(ui_Weather2_Label_Label62, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather2_Label_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather2_Label_Label62, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather2_Image_Image27 = lv_img_create(ui_Screen_Weather2);
    lv_img_set_src(ui_Weather2_Image_Image27, &ui_img_calender_noclor_png);
    lv_obj_set_width(ui_Weather2_Image_Image27, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Weather2_Image_Image27, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather2_Image_Image27, -246);
    lv_obj_set_y(ui_Weather2_Image_Image27, 171);
    lv_obj_set_align(ui_Weather2_Image_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather2_Image_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather2_Image_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen_Weather2, ui_event_Screen_Weather2, LV_EVENT_ALL, NULL);

}
