// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Screen1_screen_init(void)
{
    ui_Screen_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Screen1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_background = lv_img_create(ui_Screen_Screen1);
    lv_img_set_src(ui_Screen1_Image_background, &ui_img_bg_png);
    lv_obj_set_width(ui_Screen1_Image_background, LV_SIZE_CONTENT);   /// 354
    lv_obj_set_height(ui_Screen1_Image_background, LV_SIZE_CONTENT);    /// 356
    lv_obj_set_x(ui_Screen1_Image_background, 1);
    lv_obj_set_y(ui_Screen1_Image_background, 0);
    lv_obj_set_align(ui_Screen1_Image_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Tabview_TabView = lv_tabview_create(ui_Screen_Screen1, LV_DIR_BOTTOM, 0);
    lv_obj_set_width(ui_Screen1_Tabview_TabView, 398);
    lv_obj_set_height(ui_Screen1_Tabview_TabView, 239);
    lv_obj_set_x(ui_Screen1_Tabview_TabView, -30);
    lv_obj_set_y(ui_Screen1_Tabview_TabView, 0);
    lv_obj_set_align(ui_Screen1_Tabview_TabView, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Tabview_TabView, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Tabview_TabView,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Tabview_TabView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Tabview_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Tabpage_TabPage1 = lv_tabview_add_tab(ui_Screen1_Tabview_TabView, " ");

    ui_Screen1_Label_pigName = lv_label_create(ui_Screen1_Tabpage_TabPage1);
    lv_obj_set_width(ui_Screen1_Label_pigName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_pigName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_pigName, 62);
    lv_obj_set_y(ui_Screen1_Label_pigName, -42);
    lv_obj_set_align(ui_Screen1_Label_pigName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_pigName, "Peppa Pig");
    lv_obj_set_style_text_color(ui_Screen1_Label_pigName, lv_color_hex(0xDE6952), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_pigName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_pigName, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Image_pig = lv_img_create(ui_Screen1_Tabpage_TabPage1);
    lv_img_set_src(ui_Screen1_Image_pig, &ui_img_pig_low_png);
    lv_obj_set_width(ui_Screen1_Image_pig, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Screen1_Image_pig, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_Screen1_Image_pig, -64);
    lv_obj_set_y(ui_Screen1_Image_pig, -1);
    lv_obj_set_align(ui_Screen1_Image_pig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_pig, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_pig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label_pigIntro = lv_label_create(ui_Screen1_Tabpage_TabPage1);
    lv_obj_set_width(ui_Screen1_Label_pigIntro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_pigIntro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_pigIntro, 78);
    lv_obj_set_y(ui_Screen1_Label_pigIntro, 23);
    lv_obj_set_align(ui_Screen1_Label_pigIntro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_pigIntro, "Hello, my name is \npeppa pig,\noink~ oink~");
    lv_obj_set_style_text_color(ui_Screen1_Label_pigIntro, lv_color_hex(0xDE6952), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_pigIntro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_pigIntro, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1_Label_pigIntro, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Tabpage_TabPage2 = lv_tabview_add_tab(ui_Screen1_Tabview_TabView, " ");

    ui_Screen1_Image_monkey2 = lv_img_create(ui_Screen1_Tabpage_TabPage2);
    lv_img_set_src(ui_Screen1_Image_monkey2, &ui_img_monkey_low_png);
    lv_obj_set_width(ui_Screen1_Image_monkey2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Screen1_Image_monkey2, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_Screen1_Image_monkey2, -66);
    lv_obj_set_y(ui_Screen1_Image_monkey2, -1);
    lv_obj_set_align(ui_Screen1_Image_monkey2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_monkey2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_monkey2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label_MonkeyName3 = lv_label_create(ui_Screen1_Tabpage_TabPage2);
    lv_obj_set_width(ui_Screen1_Label_MonkeyName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_MonkeyName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_MonkeyName3, 83);
    lv_obj_set_y(ui_Screen1_Label_MonkeyName3, -43);
    lv_obj_set_align(ui_Screen1_Label_MonkeyName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_MonkeyName3, "Sun Wukong");
    lv_obj_set_style_text_color(ui_Screen1_Label_MonkeyName3, lv_color_hex(0x9C5018), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_MonkeyName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_MonkeyName3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_MonkeyIntro3 = lv_label_create(ui_Screen1_Tabpage_TabPage2);
    lv_obj_set_width(ui_Screen1_Label_MonkeyIntro3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_MonkeyIntro3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_MonkeyIntro3, 80);
    lv_obj_set_y(ui_Screen1_Label_MonkeyIntro3, 30);
    lv_obj_set_align(ui_Screen1_Label_MonkeyIntro3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_MonkeyIntro3, "Here comes your \nold pal,\nthe Monkey king!\n");
    lv_obj_set_style_text_color(ui_Screen1_Label_MonkeyIntro3, lv_color_hex(0xAC5D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_MonkeyIntro3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_MonkeyIntro3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Button_Buttonleft = lv_btn_create(ui_Screen_Screen1);
    lv_obj_set_width(ui_Screen1_Button_Buttonleft, 8);
    lv_obj_set_height(ui_Screen1_Button_Buttonleft, 7);
    lv_obj_set_x(ui_Screen1_Button_Buttonleft, -12);
    lv_obj_set_y(ui_Screen1_Button_Buttonleft, 87);
    lv_obj_set_align(ui_Screen1_Button_Buttonleft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button_Buttonleft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button_Buttonleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Button_Buttonleft, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button_Buttonleft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button_Buttonleft, 230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Button_Buttonright = lv_btn_create(ui_Screen_Screen1);
    lv_obj_set_width(ui_Screen1_Button_Buttonright, 8);
    lv_obj_set_height(ui_Screen1_Button_Buttonright, 7);
    lv_obj_set_x(ui_Screen1_Button_Buttonright, 8);
    lv_obj_set_y(ui_Screen1_Button_Buttonright, 87);
    lv_obj_set_align(ui_Screen1_Button_Buttonright, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button_Buttonright, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button_Buttonright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Button_Buttonright, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button_Buttonright, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button_Buttonright, 230, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_Tabview_TabView, ui_event_Screen1_Tabview_TabView, LV_EVENT_ALL, NULL);

}
