// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen_Screen1
void ui_Screen_Screen1_screen_init(void);
lv_obj_t * ui_Screen_Screen1;
lv_obj_t * ui_Screen1_Image_background;
void ui_event_Screen1_Tabview_TabView(lv_event_t * e);
lv_obj_t * ui_Screen1_Tabview_TabView;
lv_obj_t * ui_Screen1_Tabpage_TabPage1;
lv_obj_t * ui_Screen1_Label_pigName;
lv_obj_t * ui_Screen1_Image_pig;
lv_obj_t * ui_Screen1_Label_pigIntro;
lv_obj_t * ui_Screen1_Tabpage_TabPage2;
lv_obj_t * ui_Screen1_Image_monkey2;
lv_obj_t * ui_Screen1_Label_MonkeyName3;
lv_obj_t * ui_Screen1_Label_MonkeyIntro3;
lv_obj_t * ui_Screen1_Button_Buttonleft;
lv_obj_t * ui_Screen1_Button_Buttonright;
// CUSTOM VARIABLES

// EVENTS
//lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Tabview_TabView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_opacity_set(ui_Screen1_Button_Buttonleft, 80);
        _ui_basic_set_property(ui_Screen1_Button_Buttonleft, _UI_BASIC_PROPERTY_WIDTH,  80);
        _ui_screen_delete(&ui_Screen_Screen1);
    }
}

///////////////////// SCREENS ////////////////////

void profile_app_conf_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Screen1_screen_init();
    //ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Screen1);
}
