// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
#include "esp_brookesia.h"

// SCREEN: ui_Screen_Screen1
void ui_Screen_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen_Screen1;
extern lv_obj_t * ui_Screen1_Image_background;
void ui_event_Screen1_Tabview_TabView(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Tabview_TabView;
extern lv_obj_t * ui_Screen1_Tabpage_TabPage1;
extern lv_obj_t * ui_Screen1_Label_pigName;
extern lv_obj_t * ui_Screen1_Image_pig;
extern lv_obj_t * ui_Screen1_Label_pigIntro;
extern lv_obj_t * ui_Screen1_Tabpage_TabPage2;
extern lv_obj_t * ui_Screen1_Image_monkey2;
extern lv_obj_t * ui_Screen1_Label_MonkeyName3;
extern lv_obj_t * ui_Screen1_Label_MonkeyIntro3;
extern lv_obj_t * ui_Screen1_Button_Buttonleft;
extern lv_obj_t * ui_Screen1_Button_Buttonright;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_pig_low_png);    // assets/pig_low.png
LV_IMG_DECLARE(ui_img_monkey_low_png);    // assets/monkey_low.png

// UI INIT
void profile_app_conf_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
